### PR TITLE
Fury Mode

### PR DESCRIPTION
**Pull request by Cc618**
Hello,
I've added the **Fury Mode**.
It's not in the real Flappy Bird but it adds so much fun to the game.
We can now break pipes when we hit them.
Thank you so much for your game and enjoy my new mode !

### CODE REVIEW

**Comment by sourabhv** [comment]
Awesome PR.

It's a really fun mode but I think it makes more sense to keep it as a separate repository. I'll link your repo in the README.

**Comment by Cc618** [comment]
> Awesome PR.
> 
> It's a really fun mode but I think it makes more sense to keep it as a separate repository. I'll link your repo in the README.

Yes of course I understand absolutly your decision,
thank you so much for the link in the readme !

**Comment by sourabhv** [comment]
I think you deleted the fork?

**Comment by Cc618** [comment]
> I think you deleted the fork?

Oh I'm sorry, I'm new on GitHub and I made a small mistake !
I've recreated the repo with the same URL.

Have a good day !

**Pull request closed without merging**
